### ISSUE TITLE
TL-WN722N V.3 not working

### ISSUE THREAD

**Issue by Kry9toN** [rithvikvibhu/nh-magisk-wifi-firmware#8]
My adapter not working?whether tl wn722n v3 can't?

**Comment by Kry9toN** [comment]
letak mencari log dmesg nya dimana?

**Comment by rithvikvibhu** [comment]
First make sure you have root. Since this is a Magisk module, I'm assuming Magisk already works.

If you have a working adb on a computer,
```bash
adb shell su -c dmesg > dmesg.log
```

Or using a terminal on the phone itself,
```bash
su -c dmesg > /sdcard/dmesg.log
```

Or get any app from Play Store that does this. Search for dmesg or something.

Get the log right after plugging in the device the latest lines will be related to the adapter.

**Comment by Kry9toN** [comment]
log dmesg is empty, does the kernel on my device not support external wireless?

**Comment by rithvikvibhu** [comment]
Are you sure you have root? Most phones (none afaik) support with stock kernels. Look up custom kernels for your device. Until then, this module is useless.

**Comment by Kry9toN** [comment]
My device already root, my device xiaomi redimi 5 plus on rom PIXEL EXPERIENCE

**Comment by rithvikvibhu** [comment]
Maybe the kernel is based on pure AOSP and do not support adapters. Can't do much about that, unless you can find a custom kernel or build one yourself.

This module only adds missing firmware for devices.
